import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// Components
import Header from '@/app/Header';
import ToastProvider from '@/components/ToastProvider';

import './globals.css';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{ children: ReactNode }>) {
    return (
        <html
            lang="en"
            className={`dark ${inter.className} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col dark:text-white dark:bg-midnight">
                <ToastProvider>
                    <Header />
                    {props.children}
                </ToastProvider>
            </body>
        </html>
    );
}
